import type { ContactCentreInteraction, Route, Urgency, Risk } from '../src/shared/types.js';

type Labels = Omit<ContactCentreInteraction['groundTruth'], 'route' | 'customerValue'>;
export interface ChallengeScenario extends Labels {
  route: Route;
  subject: string;
  message: string;
}

function cases(route: Route, entries: Array<[string, string, Urgency, Risk, Risk, boolean]>): ChallengeScenario[] {
  return entries.map(([subject, message, urgency, churnRisk, fraudRisk, humanEscalation]) =>
    ({ route, subject, message, urgency, churnRisk, fraudRisk, humanEscalation }));
}

// Authored narratives: labels describe the current unresolved request, not historical keywords.
// Placeholders are filled deterministically; no customer records or live API calls are used.
export const challengeScenarios: ChallengeScenario[] = [
  ...cases('billing', [
    ['Credit on the wrong invoice', 'The credit was approved and appears in our account ledger, so I am not asking you to send money back. The next invoice still shows the old balance because the credit was attached to our closed workspace. Please reconcile the two ledgers before tomorrow’s payment run. Our bookkeeper has confirmed that all purchases are ours.', 'medium', 'low', 'low', false],
    ['Renewal following a seat reduction', 'We reduced the active seat count from {seats} to {smallSeats} before renewal. Your confirmation shows the change, but the next invoice still uses the old count. Service is working and we intend to keep it. I need a corrected invoice rather than a cancellation or a cash refund. The automatic payment is not due for another week.', 'medium', 'low', 'low', false],
    ['Recognised merchant, disputed fee', 'The statement descriptor initially looked suspicious. I checked with my partner and every purchase is recognised; nobody accessed the account without permission. The unresolved issue is a service fee of ${amount} that differs from our contract. Please explain the fee calculation before I approve the invoice. There is no transfer in progress and no request to lock the account.', 'medium', 'low', 'low', false],
    ['Invoice needed next month', 'URGENT was copied into the subject by our internal purchasing system. In reality we need a historical GST invoice for next month’s filing and can wait several days. The balance is settled and the invoice totals are correct. I only need the document reissued with the company registration detail that our accountant supplied.', 'low', 'low', 'low', false],
    ['Payment hold during hardship', 'I lost my job and cannot cover this week’s scheduled debit of ${amount} without missing rent. I need a person to discuss a payment arrangement and stop that debit before it is submitted today. I am not disputing the charge or asking to leave. An automated reminder sent me back to the standard payment screen and did not address my circumstances.', 'high', 'low', 'low', true],
    ['Suspension after a settled balance', 'The account was suspended this morning for an unpaid invoice, although our bank confirms settlement and I have the payment reference. Staff cannot process live customer orders until the payment is allocated. The app itself is healthy; the block is specifically the overdue-balance flag. Please reconcile the payment and restore billing clearance immediately.', 'critical', 'low', 'low', true],
    ['Annual versus monthly calculation', 'I selected annual billing but our purchase order assumes twelve equal monthly invoices. I can see the annual discount and acknowledge that the purchase was authorised. Before any payment leaves next week, please explain the schedule and whether the purchase order can be accommodated. I am exploring the accounting options, not requesting a refund or cancellation.', 'medium', 'low', 'low', false],
    ['Collections notice with mismatched currency', 'Your collection notice converts an invoice from NZ dollars into AU dollars and makes our settled amount look short. We have supplied both bank references twice without a reconciliation. A collection referral is scheduled for tomorrow and could affect our business. Please have someone reconcile the currency and put the referral on hold today; this is not a product outage.', 'high', 'low', 'low', true],
    ['Repeated pricing surprises', 'This is the third invoice whose usage total differs from the export, and I am beginning to compare alternatives because forecasting costs has become difficult. I have not decided to leave. The immediate request is an itemised reconciliation for {month} and a clear explanation of the meter reset date; no refund has been agreed and service remains available.', 'medium', 'medium', 'low', true],
    ['Tax treatment of a plan migration', 'Our old and new plans overlap for four days on the invoice. The account manager says this is a tax-apportionment issue, and the total is not an unauthorised card transaction. Please verify the prorated GST and issue the correct invoice. We have already approved the new plan and are not asking about its features or seeking to cancel it.', 'medium', 'low', 'low', false],
  ]),
  ...cases('technical', [
    ['Exports disagree after locale change', 'The on-screen total is correct, but an export treats decimal commas as thousands separators after we select the NZ locale. I reproduced it in two browsers with the same sample rows. Billing has confirmed the invoice is unrelated. We can use the screen totals until the report due next week, so please investigate the export transformation in the normal queue.', 'medium', 'low', 'low', false],
    ['Webhook duplicates after successful replies', 'Our receiver returns HTTP 200, but the same event arrives {retries} times with an unchanged event ID. We have enabled deduplication, so orders are no longer duplicated, yet the retry backlog is growing. Please inspect acknowledgement handling today before the scheduled promotion. The endpoint credentials have not changed and there are no unknown logins.', 'high', 'low', 'low', true],
    ['Production checkout blocked', 'The embedded checkout fails for every customer with a timeout while the admin dashboard still opens. We tried two networks and rolled back our own deployment without improvement. There is no alternative way to accept live orders and transactions are currently being lost. Please treat the failing checkout as the active incident; the invoice query earlier in the thread is already closed.', 'critical', 'low', 'low', true],
    ['A frightening error in a sandbox', 'The test environment says CRITICAL FAILURE, but this only occurs when I upload a deliberately malformed sample into an unused sandbox. Production and customer records are unaffected. I would like the validation message improved whenever the team has capacity. There is no deadline this week, no data loss and no need to interrupt the live service.', 'low', 'low', 'low', false],
    ['Renewal concern after slow reports', 'Reports now take {minutes} minutes instead of seconds after the last release. We can still download them, but the workaround is becoming frustrating and I have started comparing other tools. I am not requesting cancellation yet. Please investigate the performance regression in the normal support queue and tell me what evidence you need from our test workspace.', 'medium', 'medium', 'low', true],
    ['Search omits archived permissions', 'A colleague can open a record by its direct link but cannot find it through search. We checked her role and the permission audit shows no unauthorised changes. The problem begins only when archived projects are included in the filter. Please diagnose indexing rather than resetting her login. Other work continues and the missing search results can wait until tomorrow.', 'medium', 'low', 'low', false],
    ['MFA works, dashboard returns to login', 'The identity provider records a successful MFA check and the same user can open the mobile app. Only the browser dashboard loops back to sign-in after accepting the session cookie. Clearing cookies fixes it for one visit, then the loop returns. This appears to be session handling rather than a lost password; please investigate the reproducible browser behaviour.', 'medium', 'low', 'low', false],
    ['Timezone bug with a manual workaround', 'Appointments created in Melbourne appear an hour early for the NZ team after the daylight-saving switch. We can manually correct today’s calendar and no appointments have been missed. The original security alert was our authorised administrator changing the region setting. Please fix the timezone conversion and advise whether existing entries need regeneration.', 'medium', 'low', 'low', false],
    ['Inventory automation stopped overnight', 'The inventory job stopped sending updates even though the last run shows successful completion. Checkout is still open, but warehouse staff need accurate stock before dispatch this afternoon. We can pause a few items manually for now. Please inspect the scheduler and event history today; nobody is asking for a refund or alleging unauthorised activity.', 'high', 'low', 'low', true],
    ['Audit trail missing during live edits', 'Users are changing customer records now, but those changes are not appearing in the audit trail. We cannot safely continue regulated processing without a record of who changed what, and there is no alternate capture mechanism. Access logs show only known staff. Please address the audit persistence failure immediately rather than treating this as a question about retention features.', 'critical', 'low', 'low', true],
  ]),
  ...cases('retention', [
    ['Keep the account, reduce the footprint', 'We have finished a project and need to reduce the subscription from {seats} seats to {smallSeats}. The product works and no payment is disputed. Unless you can offer a smaller arrangement, we will terminate the subscription at the next renewal. Please discuss an option that lets us stay; the export instructions in the earlier email were only preparation.', 'medium', 'high', 'low', true],
    ['Exit despite a resolved bug', 'Engineering fixed the export defect and I appreciate that response. Nevertheless, we have chosen another provider and want to end this account at the end of the month. I need confirmation of the cancellation date and the steps to stop renewal. There is no outstanding refund or security incident, and another troubleshooting session will not change the decision.', 'medium', 'high', 'low', true],
    ['Negotiating before a decision', 'Another supplier quoted a lower rate for the same seat count. We are still comparing and have not approved a move. Could someone explain whether a loyalty offer or different plan would make staying sensible? Our current service is working and we are happy to discuss this tomorrow; I am not asking for an invoice correction.', 'medium', 'medium', 'low', true],
    ['Seasonal pause or final closure', 'The business shuts for part of the year. I would prefer to pause billing and keep the workspace, but if a pause is unavailable we will close it entirely. This is not a forgotten-password problem; I can sign in and have already downloaded the records. Please discuss the retention options before we submit the closure form next week.', 'medium', 'high', 'low', true],
    ['Renewal cut-off this afternoon', 'Auto-renewal closes this afternoon and we have approval to switch suppliers unless an agreed discount is applied before that cut-off. The invoice itself is correct under the existing contract. I need a human to confirm a save offer or stop renewal today, rather than send the standard pricing page again.', 'high', 'high', 'low', true],
    ['Price increase after years of use', 'I have used the service for years, but the new price no longer fits our budget. I am weighing up alternatives and would like to understand a lower-cost way to remain. This is a conversation about whether to stay, not a disputed debit or demand for money back. There is no decision needed before the end of this week.', 'medium', 'medium', 'low', true],
    ['Partial migration already underway', 'We have moved half the team to another tool and will remove the remaining seats next month unless the account manager can agree a smaller package. Support resolved our login issue, so please do not restart that case. I need someone who can handle the reduction or cancellation terms, with written confirmation of what will renew.', 'medium', 'high', 'low', true],
    ['Export request with departure intent', 'I need our data exported because we are leaving the platform, not because the export function is broken. The replacement contract has been signed and I have authority to terminate this subscription. Please coordinate the exit and stop future renewal while allowing read access through the agreed notice period. No reimbursement is requested.', 'medium', 'high', 'low', true],
    ['Close before a cost deadline', 'Our finance director has instructed us to stop this service today before a new annual commitment starts. We recognise the existing balance and are not disputing previous charges. Please have someone action the termination before the afternoon cut-off and confirm the effective date. We will not approve another troubleshooting or sales call in place of that request.', 'high', 'high', 'low', true],
    ['Plan viability after changed usage', 'Our usage fell sharply when a contract ended, so paying for the current tier may no longer be worthwhile. I am considering leaving but have not made a decision. Could we discuss a smaller tier or a temporary arrangement in the usual queue? Everything works; please focus on keeping the relationship viable rather than investigating a technical fault.', 'medium', 'medium', 'low', true],
  ]),
  ...cases('fraud_security', [
    ['Refund wording hides an unknown purchase', 'The subject of the form says refund because that was the closest menu option, but I never authorised the purchase of ${amount}. I still have my card and nobody in the household recognises the merchant. Another payment attempt just appeared while I was checking the statement. Please prevent further activity and investigate the compromise immediately.', 'critical', 'low', 'high', true],
    ['Reset after an unknown email change', 'I first thought I had forgotten my password. The recovery screen now shows an email address I have never used, and a notification says the account contact was changed overnight. I did not approve that change. A payment is pending right now. Please secure the account immediately instead of sending another reset link to the unknown address.', 'critical', 'low', 'high', true],
    ['Caller knew the invoice amount', 'Someone phoned with our exact invoice amount and asked me to install a remote-support tool. I declined and did not share a code or password. Our legitimate account manager cannot verify that the caller was staff. There is no observed loss, but please check the attempted social engineering today and tell us which official channel to use.', 'high', 'low', 'medium', true],
    ['Verification link before any disclosure', 'An email says our workspace will close unless I verify through a link with an unfamiliar domain. I have not opened the link or entered credentials, and signing in through the usual address works. Could your security team verify whether this is phishing today? The account is functioning, so this is not an access-recovery request.', 'high', 'low', 'medium', true],
    ['One-time code followed by a transfer', 'I gave a one-time code to a caller who claimed to be correcting an invoice. Immediately afterwards an unauthorised transfer of ${amount} appeared and another is being prepared. I now understand the caller was not our supplier. Please stop further transfers and secure the account immediately; the billing explanation was part of the scam.', 'critical', 'low', 'high', true],
    ['New sessions after revocation', 'We revoked an unknown device session yesterday, but the same unrecognised location signed in again today. The audit shows exports performed by that session, and our administrator denies authorising them. Please investigate the continuing compromise and restrict the active session now. All ordinary staff login problems have already been resolved.', 'critical', 'low', 'high', true],
    ['Suspicious attachment left unopened', 'A message claiming to be a complaint from a customer includes an executable attachment and asks us to disable scanning. Nobody has opened it and our systems show no incident. We need a human to verify the sender and advise on safe reporting today. The complaint text may be a lure; there is no actual service complaint to resolve in this account.', 'high', 'low', 'medium', true],
    ['Card purchases after a frozen account', 'The account shows new purchases after we requested a freeze for a stolen card. These were not made by our staff and the alerts continue to arrive now. The earlier refund case relates to a legitimate return and is separate. Please address the ongoing unauthorised spending immediately, including whether the freeze took effect.', 'critical', 'low', 'high', true],
    ['Reset emails with no confirmed entry', 'Several reset emails arrived for requests I did not make. The account email and recent activity still look normal, and I have not clicked any links. I do not know whether someone is testing access or whether there is an error. Please review the suspicious attempts today; I can still sign in and do not need routine recovery help.', 'high', 'low', 'medium', true],
    ['Beneficiary changed during payment', 'The supplier name looks familiar, but the stored beneficiary account was changed without our finance team approving it. A transfer is due to release within minutes. We verified the original details with the supplier through our existing contact. Please stop the pending payment and investigate the unauthorised change immediately, rather than merely correct the invoice display.', 'critical', 'low', 'high', true],
  ]),
  ...cases('account_access', [
    ['Old phone removed before enrolment', 'I traded in the old phone before transferring the authenticator. The password works but I cannot pass the second factor; all recent activity is recognised. Please arrange recovery using your identity checks. The account has no live transactions and I can work offline until tomorrow. This is a lost-factor problem, not a reported takeover.', 'medium', 'low', 'low', true],
    ['Former employee owns the recovery address', 'Our authorised administrator left and the recovery address belongs to their closed mailbox. No suspicious changes occurred, but we need verified ownership transferred to the current administrator. The remaining users can work normally. Please explain the identity and authority checks for recovery in the normal queue rather than diagnosing a product outage.', 'medium', 'low', 'low', true],
    ['Urgent subject, archived account', 'I marked the request urgent out of habit, but this is an old personal account I only need for records next month. The password was forgotten and the recovery email is delayed. There are no active payments or unknown sign-ins. Please help with the ordinary reset process when available; waiting a few days will not cause harm.', 'low', 'low', 'low', false],
    ['Reset link already used by mail preview', 'The reset email arrives, but the link reports that it has already been used as soon as I open it. Our mail service previews links automatically. I still control the verified mailbox and can receive codes. Please provide the supported alternative recovery method; I do not need an investigation into unknown purchases or a change of account owner.', 'medium', 'low', 'low', false],
    ['Identity check needs accessibility help', 'The document check asks me to perform a camera movement I cannot physically complete. I have the correct credentials and there is no security alert. Please arrange an accessible manual verification route with a person. I can wait until tomorrow, but repeating the same automated instructions will not let me regain access.', 'medium', 'low', 'low', true],
    ['Authorised MFA change, recovery still blocked', 'The MFA change in the audit was made by our own administrator and has been verified. Unfortunately the recovery number was typed incorrectly and none of the codes reaches us. Please verify ownership and restore access today because payroll approval is due this afternoon. Do not treat the recognised change as an account compromise.', 'high', 'low', 'low', true],
    ['Account locked before live approvals', 'I entered the wrong password too many times and triggered the lockout. I recognise every activity entry, but I am the only approver for payments that must be released today. Please arrange verified unlocking today. The service works for everyone else and there is no evidence of fraud or a product-wide login defect.', 'high', 'low', 'low', true],
    ['Email alias changed after a merger', 'Our company renamed its email domain and my former alias no longer receives reset messages. Other colleagues can use the product. I need a human to verify the organisation and update my recovery contact so I can regain access; the records and subscription should stay in place. This is not a request for cancellation or a new plan.', 'medium', 'low', 'low', true],
    ['A disabled dormant login', 'The login says the account is dormant after a year without activity. I only want to reactivate it and read the old records. There are no unexpected changes, financial disputes or urgent deadlines. Please tell me the standard steps for reactivation in the normal queue rather than directing me to the complaints team.', 'medium', 'low', 'low', false],
    ['Recovery concern becoming a decision factor', 'I have tried the recovery process repeatedly without regaining access to my own account. I am starting to consider a different service, but have not decided to close this one. Please arrange verified manual recovery; that is the outstanding request. There is no unknown activity and no immediate financial deadline, so tomorrow is acceptable.', 'medium', 'medium', 'low', true],
  ]),
  ...cases('complaints', [
    ['Resolved payment, unresolved treatment', 'The payment error has been corrected and the money is back. What remains is my formal complaint about the agent who dismissed my accessibility request and ended the call. I want that conduct reviewed and a written outcome. I am not asking you to reopen the refund or cancel the service; a complaints specialist should own the response.', 'medium', 'low', 'low', true],
    ['Deadline for an external complaint', 'The technical fault is fixed, but three promised callbacks never happened. I have given you until this afternoon to respond to my formal service complaint before I submit it to the ombudsman. Please provide a human review and complaint reference today. No additional troubleshooting or replacement invoice is needed.', 'high', 'low', 'low', true],
    ['No departure decision yet', 'I have not decided to leave, but after repeated broken promises I am comparing other providers. My current request is a formal review of the handling of my case and a written response from a complaints specialist. The original login issue is resolved. Please do not substitute a retention discount for investigating what happened.', 'medium', 'medium', 'low', true],
    ['Complaint about an incorrect assurance', 'An agent told me an account setting had been updated when it had not. Another agent has now corrected the setting, so I am no longer asking for general help. I want the misleading assurance formally investigated and the outcome recorded. There is no ongoing outage or deadline today, and I remain a customer.', 'medium', 'low', 'low', true],
    ['Regulator response due today', 'Your complaint acknowledgement says a response would arrive yesterday, but nothing came. The regulator has requested our chronology by the end of today. I need a complaints manager to review the missed commitment and provide a written status today. The charges in the original case are now settled and are not the unresolved request.', 'high', 'low', 'low', true],
    ['Repeated transfers without ownership', 'I was sent from billing to technical and then back again, with each person asking me to repeat the history. The underlying issue was eventually fixed. Please register a formal complaint about the repeated transfers and assign someone to provide an outcome. I am frustrated but have not threatened to leave or asked for money back.', 'medium', 'low', 'low', true],
    ['Privacy handling complaint, no intrusion', 'A verified staff member discussed my case in a shared reception area despite my request for privacy. There is no indication of an account intrusion or unauthorised login. I want the handling formally reviewed and a written complaint outcome. The account remains usable; please address the conduct rather than send password-reset instructions.', 'medium', 'low', 'low', true],
    ['Dismissed interpreter request', 'I requested an interpreter and was told to ask a child to translate instead. Another agent later arranged the interpreter, so that immediate problem is solved. Please record a formal complaint and have a person review the treatment. I am not asking about product language settings or requesting account closure.', 'medium', 'low', 'low', true],
    ['Service complaint after compensation', 'The goodwill payment was received in full, but it does not answer my complaint about how the incident was handled. I want the timeline, missed commitments and review outcome in writing. I am beginning to question whether to remain a customer but have not decided. Please keep the complaints review open instead of marking it solved by the refund.', 'medium', 'medium', 'low', true],
    ['Incorrect closure of a formal case', 'I received a notice saying my complaint was withdrawn even though I did not withdraw it. The routine account change has been completed, but I still need the formal case reopened and reviewed. There is no immediate deadline or active security incident. Please assign a complaints specialist and confirm the reference and expected response time.', 'medium', 'low', 'low', true],
  ]),
  ...cases('refunds', [
    ['Approved refund went to the old card', 'The duplicate payment was recognised as our authorised purchase and a refund was approved. It went to a card that has since been closed and the bank says it returned to you. I am not alleging fraud or asking to cancel the account. Please trace the refund and arrange the approved money back to the supported destination.', 'medium', 'low', 'low', true],
    ['Partial return, no disputed purchase', 'I bought {seats} add-ons by mistake, used only {smallSeats}, and the agent agreed to reimburse the unused items. The credit received is ${smallAmount}, below the approved amount of ${amount}. Please check the approved refund calculation and return the remainder. I recognise the purchase and want to keep the subscription; the missing reimbursement is the outstanding issue.', 'medium', 'low', 'low', true],
    ['Cancellation finished, refund remains', 'The subscription is already cancelled and written confirmation shows renewal stopped. I am only contacting you because the refund approved for the unused period has not arrived after two weeks. Please investigate the refund status and expected settlement date. There is no save-offer discussion or technical fault left to address.', 'medium', 'low', 'low', true],
    ['Small unused purchase within return window', 'I accidentally purchased a small optional add-on for ${smallAmount} and have not activated it. The published return window is still open. Please process the standard refund to the original payment method whenever the routine queue reaches it. My account and core subscription should remain active, and I can wait several days.', 'low', 'low', 'low', false],
    ['Refund needed during hardship', 'The approved refund of ${amount} is overdue and I need it for rent due today. I have already provided the correct payment destination and the refund reference. Please have a person trace or release it today because the delay is causing financial hardship. This is not a request to explain the original invoice or investigate an unknown purchase.', 'high', 'low', 'low', true],
    ['Merchant reversal recognised by both sides', 'The merchant confirms our legitimate order was returned and the reversal accepted. My balance still includes the settled charge a week later. Please trace that reversal and complete the money-back process; the original order was authorised. The screenshot about suspicious purchases earlier in the thread belongs to an unrelated resolved case.', 'medium', 'low', 'low', true],
    ['Service retained after a return', 'The replacement service is working and we intend to keep it. An agreed refund for the faulty optional accessory was processed only in part, despite a return receipt covering the whole item. Please reconcile the return and send the remaining approved amount. A discount on next year’s subscription would not resolve the outstanding reimbursement.', 'medium', 'low', 'low', true],
    ['Refund destination confirmation', 'I accepted the offer of a refund and the approval reference is recorded, but the payout form keeps selecting an expired card. The refund has not been released yet. Please help complete the approved refund through an allowed method without asking me to share card details in this conversation. The purchase and account activity are recognised.', 'medium', 'low', 'low', true],
    ['Goodwill promise after an outage', 'The outage is fixed and there is nothing left for engineering to diagnose. Your agent promised a goodwill refund of ${amount}, but the credit received does not match the written approval. Please check the approval and complete the reimbursement. We are not closing the account or lodging a separate conduct complaint at this point.', 'medium', 'low', 'low', true],
    ['Routine refund status with no deadline', 'The refund for an unused optional purchase was approved yesterday, and I understand the ordinary settlement window is several business days. I only want to confirm that it has entered the normal process. There is no urgent need for the funds and no request to bypass the queue. All purchases were authorised and the account remains active.', 'low', 'low', 'low', false],
  ]),
  ...cases('product_info', [
    ['Security features before purchase', 'Our procurement form mentions account takeover and suspicious transactions as risks we need to manage. We have not experienced either; we are assessing a possible new subscription. Can you explain which plans include device audit logs and administrator alerts? This is a feature enquiry for next month’s selection process, not a report of an active incident.', 'low', 'low', 'low', false],
    ['Cancellation policy as due diligence', 'The checklist asks how cancellation and data export work before we sign a contract. We do not have an account to close and have made no purchase. Please explain the notice period, export formats and what read access remains at the end of a term. We can review the answer over the next few days.', 'low', 'low', 'low', false],
    ['Expected API limits for planned launch', 'We are planning an integration with roughly {seats} staff using it, but have not sent any production requests. The sample code includes timeout handling as a design precaution. Please confirm the published rate limits and whether a larger plan changes them. There is no API failure to diagnose; this is capacity planning before purchase.', 'low', 'low', 'low', false],
    ['Audit retention comparison', 'Our policy requires an audit history for a particular period and we are comparing the available plans. No records are missing and no customer data has been deleted. Please explain the retention options and whether exports preserve actor and timestamp fields. The procurement decision is next week, so the normal information queue is suitable.', 'low', 'low', 'low', false],
    ['Quote by this afternoon', 'We need a quote for {seats} users before the tender closes this afternoon. The questions concern consolidated billing, audit features and implementation options, not an invoice already issued. Please prioritise a response today so we can submit the procurement form. There is no outage, financial loss or suspected account compromise.', 'high', 'low', 'low', false],
    ['Sandbox behaviour described as a question', 'We have not installed the product yet. A consultant mentioned that some providers limit webhook retries, and we want to know what yours supports. The words failed event in the attached checklist are a hypothetical test case. Please explain retry configuration and supported acknowledgement codes rather than opening an incident for a live endpoint.', 'low', 'low', 'low', false],
    ['Privacy questions before a trial', 'Our legal checklist asks where data is hosted and how deletion works when a trial ends. This does not refer to a privacy incident or missing account records. Could you explain the supported hosting regions and documented deletion process? We are evaluating options and do not need a personalised legal interpretation or a same-day response.', 'low', 'low', 'low', false],
    ['Accessibility capability enquiry', 'Before choosing the software we want to know which screens support keyboard navigation and screen readers. Nobody is locked out of an existing account and there is no current service complaint. Please provide the feature documentation and trial options when available. We can use that information in next week’s procurement review.', 'low', 'low', 'low', false],
    ['Business support inclusions', 'We are considering the Business plan and want to know whether a named support contact and consolidated statements are included. The current invoice is correct and the existing service works. Please explain the features and upgrade process in the normal queue. There is no request for a loyalty offer or intention to leave.', 'medium', 'low', 'low', false],
    ['Mobile parity before rollout', 'We are designing a rollout where most staff use Android devices. Can mobile users approve requests and export reports, or do those functions require the browser version? Nobody has reported a broken export or app crash; this is a capability question before we choose devices. We can wait a few days for an accurate feature answer.', 'low', 'low', 'low', false],
  ]),
  ...cases('general_service', [
    ['Postal address after an authorised move', 'We moved office and want future printed statements sent to the new mailing address. The login email should stay unchanged and everyone can access the account. There is no dispute about past charges and no unexplained change. Please tell us the ordinary address-update process whenever the routine queue reaches this request.', 'low', 'low', 'low', false],
    ['Download history for internal records', 'I want a list of old support case references for our internal filing. All of those cases are closed and I am not asking to reopen a complaint. The account works and there is no evidence of unauthorised access. Please show me where to download the case history; our filing project does not start until next week.', 'low', 'low', 'low', false],
    ['Language preference without an outage', 'Please change the language used for ordinary account emails. The translated messages in the older thread concerned a resolved access problem, and I do not need password recovery now. I can use the current messages until next week. This is a routine communication preference change, not a new product feature request.', 'low', 'low', 'low', false],
    ['Authorised contact instructions', 'I would like instructions for adding our existing bookkeeper as an authorised contact. There is no ownership dispute, nobody is locked out and we have not yet submitted documents. Please explain the standard process and where the account owner should start. This can wait several days and no immediate financial decision is involved.', 'low', 'low', 'low', false],
    ['Statement format for an archive', 'The statement totals are correct and all payments are recognised. I just need an accessible copy of the historical statement for our archive rather than the current image-only attachment. Please arrange the ordinary document format change in the normal queue. There is no disputed invoice, refund request or threat to leave.', 'medium', 'low', 'low', false],
    ['Opening hours around a holiday', 'Our team will be away during the public holiday and I need to know the ordinary support hours and callback options. The word emergency appears in our internal contact template, but there is no current emergency or outage. Please provide the schedule when convenient so I can finish the contact sheet next week.', 'low', 'low', 'low', false],
    ['Confirm an existing name change', 'The account name was updated after we supplied the requested documents. I can see the new name in the profile and only need confirmation that future correspondence will use it too. Access and payment details remain correct. Please check the saved preference in the normal queue; this is not an identity-recovery or ownership dispute.', 'low', 'low', 'low', false],
    ['Marketing messages after an opt-out', 'I switched off promotional email yesterday and want to confirm that the preference was saved. I understand an already queued campaign may still arrive. Service alerts should remain enabled and there is no formal complaint or account cancellation request. Please confirm the routine preference when you have capacity.', 'low', 'low', 'low', false],
    ['Branch information for a planned visit', 'Our records team may visit a service location next month to collect historical documents. Could you tell me which location handles that and whether an appointment is needed? There is no active case deadline, disputed charge or safety concern. The visit is simply an administrative task that we are planning ahead.', 'low', 'low', 'low', false],
    ['Copies of settled correspondence', 'Please send copies of the closure letters for two resolved support cases. One was about a suspicious email and the other about a refund, but both have written outcomes and no remaining issue. I need the letters for our archive rather than a new investigation or reimbursement. This can wait until next week.', 'low', 'low', 'low', false],
  ]),
];
